apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt-job
  labels:
    app: letsencrypt
spec:
  template:
    metadata:
      name: letsencrypt
      labels:
        app: letsencrypt
    spec:
      containers:
      - image: quay.io/hiphipjorge/kube-nginx-letsencrypt:latest
        name: letsencrypt
        imagePullPolicy: Always
        ports:
        - name: letsencrypt
          containerPort: 80
        env:
        - name: DOMAINS
          value: markcardiff.tk
        - name: EMAIL
          value: mark.cardiff@gmail.com
        - name: SECRET
          value: letsencrypt-certs
        - name: DEPLOYMENT
          value: nginx-deployment
      restartPolicy: Never
