apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "ingress-service"
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.global-static-ip-name: 35.244.202.222
    networking.gke.io/managed-certificates: certificate
  labels:
    # Timestamp used in order to force reload of the secret
    last_updated: "1494099933"
spec:
  tls:
  - hosts:
    - markcardiff.tk
    secretName: letsencrypt-certs
  rules:
  - host: markcardiff.tk
    http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: nginx-service
          servicePort: 80
