#allow all
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: default
spec:
  podSelector: {} 
  ingress: 
  - {}
  policyTypes:
  - Ingress

---

#kind: NetworkPolicy
#apiVersion: networking.k8s.io/v1
#metadata:
#  name: default-deny-all
#  namespace: default
#spec:
#  podSelector: {}
#  ingress: []

---

#kind: NetworkPolicy
#apiVersion: networking.k8s.io/v1
#metadata:
#  name: web-deny-all
#spec:
#  podSelector:
#    matchLabels:
#      app: db
#  ingress: []

---

#kind: NetworkPolicy
#apiVersion: networking.k8s.io/v1
#metadata:
#  name: allow
#spec:
#  podSelector:
#    matchLabels:
#      app: db
#  ingress:
#  - from:
#      - podSelector:
#          matchLabels:
#            app: php
