apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
#      - name: www-disk
 #       persistentVolumeClaim:
  #        claimName: www-disk
      - name: nginx-config
        configMap:
          name: confnginx
      containers:
      - name: nginx
        image: markcardiff/nginxerver:v5
        volumeMounts:
         - name: nginx-config
           mountPath: /etc/nginx/conf.d
#         - name: www-disk
 #          mountPath: /usr/share/nginx/html
        ports:
         - containerPort: 80





#        ports:
 #     - containerPort: 80
