apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  selector:
    matchLabels:
      app: php
  replicas: 2
  template:
    metadata:
      labels:
        app: php
    spec:
      volumes:
#      - name: www
#        hostPath:
#          path: ./www
      containers:
      - name: php
        image: markcardiff/php-fpm-mysqli:v3
        imagePullPolicy: Always
#        volumeMounts:
#         - name: www
#           mountPath: /usr/share/nginx/html
#        ports:
 #     - containerPort: 9000
